modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"
issueTrackerURL="https://github.com/CreateTechified/TechifiedOres/issues/"
clientSideOnly=false

[[mods]]
modId="techifiedores"
version="1.0.0"
displayName="TechifiedOres" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="examplemod.png"
#credits=""
authors="wrldmap, pineapple"
displayTest="MATCH_VERSION"
description='''The funny ore mod, but I actually learned how to code.'''

[[dependencies.techifiedores]]
modId="forge"
mandatory=true
versionRange="[47.1.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.techifiedores]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1, 1.21)"
ordering="NONE"
side="BOTH"

#[features.unshatteredcore]
#openGLVersion="[3.2,)"